using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ExampleAbpApplicationLayer.Products
{
    public class Product : ProductBase
    {
        //<suite-custom-code-autogenerated>
        protected Product()
        {

        }

        public Product(Guid id, string name, float price, bool isActive, string? desc = null)
            : base(id, name, price, isActive, desc)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}