using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ExampleAbpApplicationLayer.Products
{
    public class ProductManager : ProductManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ProductManager(IProductRepository productRepository)
            : base(productRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}