apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: "{{ .Release.Name }}-{{ .Chart.Name }}"
        ports:
        - name: "http"
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /health-status
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        env:
        - name: "DOTNET_ENVIRONMENT"
          value: "{{ .Values.global.dotnetEnvironment }}"
        - name: "ConnectionStrings__Default"
          value: "{{ .Values.global.connectionStrings.default | replace "[RELEASE_NAME]" .Release.Name }}"
        - name: "App__SelfUrl"
          value: "{{ include "abpsolution1.hosts.authserver" . }}"
        - name: "App__HealthUiCheckUrl"
          value: "http://{{ .Release.Name }}-authserver/health-status"
        - name: "App__CorsOrigins"
          value: "https://*.AbpSolution1.com, {{ include "abpsolution1.hosts.httpapi" . }},{{ include "abpsolution1.hosts.angular" . }}"
        - name: AngularUrl
          value: "{{ include "abpsolution1.hosts.angular" . }}"
        - name: App__RedirectAllowedUrls
          value: "{{ include "abpsolution1.hosts.angular" . }}"
        - name: App__DisablePII
          value: "{{ .Values.global.disablePII }}"
        - name: "AuthServer__Authority"
          value: "{{ include "abpsolution1.hosts.authserver" . }}"
        - name: "AuthServer__RequireHttpsMetadata"
          value: "false"
        - name: "Redis__Configuration"
          value: "{{ .Release.Name }}-redis"
        - name: "StringEncryption__DefaultPassPhrase"
          value: "{{ .Values.global.stringEncryptionDefaultPassPhrase }}"
        - name: "AbpStudioClient__StudioUrl"
          value: "{{ .Values.global.abpStudioClient.studioUrl }}"
        - name: "AbpStudioClient__IsLinkEnabled"
          value: "{{ .Values.global.abpStudioClient.isLinkEnabled }}"