export const HTTP_METHODS = ['GET', 'POST', 'DELETE', 'PUT', 'HEAD', 'CONNECT', 'OPTIONS', 'TRACE'];

export const HTTP_STATUS_CODES = [
  { code: 100, message: 'Continue' },
  { code: 101, message: 'Switching protocols' },
  { code: 102, message: 'Processing' },
  { code: 103, message: 'Early hints' },
  { code: 200, message: 'OK' },
  { code: 201, message: 'Created' },
  { code: 202, message: 'Accepted' },
  { code: 203, message: 'Non-authoritative information' },
  { code: 204, message: 'No content' },
  { code: 205, message: 'Reset content' },
  { code: 206, message: 'Partial content' },
  { code: 207, message: 'Multi-status' },
  { code: 208, message: 'Already registered' },
  { code: 226, message: 'I am used' },
  { code: 300, message: 'Multiple choices' },
  { code: 301, message: 'Moved permanently' },
  { code: 302, message: 'Found' },
  { code: 303, message: 'See other' },
  { code: 304, message: 'Not modified' },
  { code: 305, message: 'Use proxy' },
  { code: 306, message: 'Switch proxy' },
  { code: 307, message: 'Temporary redirect' },
  { code: 308, message: 'Permanent redirect' },
  { code: 400, message: 'Bad request' },
  { code: 401, message: 'Unauthorized' },
  { code: 402, message: 'Payment required' },
  { code: 403, message: 'Forbidden' },
  { code: 404, message: 'Not Found' },
  { code: 405, message: 'Method not allowed' },
  { code: 406, message: 'Not acceptable' },
  { code: 407, message: 'Proxy authentication required' },
  { code: 408, message: 'Request timeout' },
  { code: 409, message: 'Conflict' },
  { code: 410, message: 'Gone' },
  { code: 411, message: 'Length required' },
  { code: 412, message: 'Precondition failed' },
  { code: 413, message: 'Payload too large' },
  { code: 414, message: 'Request-URI too long' },
  { code: 415, message: 'Unsupported media type' },
  { code: 416, message: 'Requested range not satisfiable' },
  { code: 417, message: 'Expectation failed' },
  { code: 421, message: 'Misdirected request' },
  { code: 423, message: 'Locked' },
  { code: 424, message: 'Failed dependency' },
  { code: 426, message: 'Upgrade required' },
  { code: 428, message: 'Precondition required' },
  { code: 429, message: 'Too many requests' },
  { code: 431, message: 'Request header fields too large' },
  { code: 451, message: 'Unavailable for legal reasons' },
  { code: 500, message: 'Internal server error' },
  { code: 501, message: 'Not implemented' },
  { code: 502, message: 'Bad gateway' },
  { code: 503, message: 'Service unavailable' },
  { code: 504, message: 'Gateway timeout' },
  { code: 505, message: 'HTTP version not supported' },
  { code: 506, message: 'Variant also negotiates' },
  { code: 507, message: 'Insufficient storage' },
  { code: 508, message: 'Loop detected' },
  { code: 510, message: 'Not extended' },
  { code: 511, message: 'Network authentication required' },
];
