using ExampleAbpApplicationLayer.Shared;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using ExampleAbpApplicationLayer.Permissions;
using ExampleAbpApplicationLayer.Products;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using ExampleAbpApplicationLayer.Shared;

namespace ExampleAbpApplicationLayer.Products
{
    public class ProductsAppService : ProductsAppServiceBase, IProductsAppService
    {
        //<suite-custom-code-autogenerated>
        public ProductsAppService(IProductRepository productRepository, ProductManager productManager, IDistributedCache<ProductDownloadTokenCacheItem, string> downloadTokenCache)
            : base(productRepository, productManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}