using ExampleAbpApplicationLayer.Products;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ExampleAbpApplicationLayer.OrderItems
{
    public class OrderItem : OrderItemBase
    {
        //<suite-custom-code-autogenerated>
        protected OrderItem()
        {

        }

        public OrderItem(Guid id, Guid orderId, Guid productId, int qty, float price, float totalPrice, string? productName = null)
            : base(id, orderId, productId, qty, price, totalPrice, productName)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}