using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ExampleAbpApplicationLayer.OrderItems
{
    public class OrderItemManager : OrderItemManagerBase
    {
        //<suite-custom-code-autogenerated>
        public OrderItemManager(IOrderItemRepository orderItemRepository)
            : base(orderItemRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}