using Volo.Abp.Identity;
using ExampleAbpApplicationLayer.Enums.Orders;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ExampleAbpApplicationLayer.Orders
{
    public class Order : OrderBase
    {
        //<suite-custom-code-autogenerated>
        protected Order()
        {

        }

        public Order(Guid id, Guid? identityUserId, DateTime orderDate, float totalAmount, OrderStatus status)
            : base(id, identityUserId, orderDate, totalAmount, status)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}