using ExampleAbpApplicationLayer.Enums.Orders;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ExampleAbpApplicationLayer.Orders
{
    public class OrderManager : OrderManagerBase
    {
        //<suite-custom-code-autogenerated>
        public OrderManager(IOrderRepository orderRepository)
            : base(orderRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}