using ExampleAbpApplicationLayer.Shared;
using ExampleAbpApplicationLayer.Products;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using ExampleAbpApplicationLayer.Permissions;
using ExampleAbpApplicationLayer.OrderItems;

namespace ExampleAbpApplicationLayer.OrderItems
{
    public class OrderItemsAppService : OrderItemsAppServiceBase, IOrderItemsAppService
    {
        //<suite-custom-code-autogenerated>
        public OrderItemsAppService(IOrderItemRepository orderItemRepository, OrderItemManager orderItemManager, IRepository<ExampleAbpApplicationLayer.Products.Product, Guid> productRepository)
            : base(orderItemRepository, orderItemManager, productRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}